# nonk8s
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "dask-modules"
  tags:
  - "public"
  - "internal"
spec:
  type: "library"
  lifecycle: "production"
  owner: "dataplattform"
  system: "dataplattformtjenester"
