name: Build and publish Docker Image

on:
  workflow_call:
    inputs:
      context_path:
        required: true
        type: string

    outputs:
      image_url:
        value: ${{ jobs.build.outputs.image_url }}

env:
  REGISTRY: ghcr.io
  CONTEXT_PATH: ${{ inputs.context_path }}

jobs:
  build:
    name: Build and publish container image
    runs-on: ubuntu-latest
    outputs:
      image_url: ${{ steps.set_output.outputs.image_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Check for changes in context path
        id: check_changes
        run: |
          if git diff --quiet HEAD^ HEAD -- ${CONTEXT_PATH} && [ "${MANUAL_DEPLOY_TRIGGER}" = false ]; then
            echo "No changes in ${CONTEXT_PATH}. Skipping build."
            echo "skip_build=true" >> "$GITHUB_OUTPUT"
          else
            echo "skip_build=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Login to Github Container Registry
        if: steps.check_changes.outputs.skip_build == 'false'
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        if: steps.check_changes.outputs.skip_build == 'false'
        id: build-docker
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          file: ${{ env.CONTEXT_PATH }}/Dockerfile
          context: ${{ env.CONTEXT_PATH }}
          push: ${{ !github.event.pull_request.draft }}
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:latest

      - name: Set output with build values
        if: steps.check_changes.outputs.skip_build == 'false'
        id: set_output
        run: |
          echo "image_url=${{ env.REGISTRY }}/${{ github.repository }}@${STEPS_BUILD_DOCKER_OUTPUTS_DIGEST}" >> "$GITHUB_OUTPUT"
        env:
          STEPS_BUILD_DOCKER_OUTPUTS_DIGEST: ${{ steps.build-docker.outputs.digest }}
