name: Create pull request to repository

on:
  workflow_dispatch:
    inputs:
      repo:
        description: "Repository to create pull request for"
        required: true
        type: string

env:
  GITHUB_TOKEN: ${{ secrets.DASK_ONBOARDING_PAT }}
  REPO: ${{ inputs.repo }}

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          path: "current-repo"

      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: kartverket/${{ env.REPO }}
          ref: main
          token: ${{ env.GITHUB_TOKEN }}
          path: "target-repo"

      - name: Modify files
        working-directory: current-repo
        run: |
          python scripts/test.py

      - name: Commit and Push to target repository
        working-directory: target-repo
        run: |
          git config --global user.name "DASK CI"
          git config --global user.email "noreply@kartverket.no"
          git checkout -b test-workflow
          git add .
          git commit -m "Update file"
          git push origin test-workflow
