name: Create pull request to repository

on:
  workflow_dispatch:
    inputs:
      target_repo:
        description: "Repository to create pull request for"
        required: true
        type: string
      file_to_modify_path:
        description: "File to modify"
        required: true
        type: string
      script:
        description: "Script to run"
        required: true
        type: string

env:
  GITHUB_TOKEN: ${{ secrets.DASK_ONBOARDING_PAT }}
  TARGET_REPO: ${{ inputs.target_repo }}
  FILE_TO_MODIFY_PATH: ${{ inputs.file_to_modify_path }}
  SCRIPT: ${{ inputs.script }}

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_wrapper: false

      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          path: "current-repo"

      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: kartverket/${{ env.TARGET_REPO }}
          ref: main
          token: ${{ env.GITHUB_TOKEN }}
          path: "target-repo"

      - name: Modify files
        working-directory: current-repo
        run: |
          python scripts/${{ env.SCRIPT }} ../target-repo/${{ env.FILE_TO_MODIFY_PATH }}

      - name: Commit and Push to target repository
        working-directory: target-repo
        run: |
          git config --global user.name "DASK CI"
          git config --global user.email "noreply@kartverket.no"
          git checkout -b test-workflow
          terraform fmt -recursive
          git add .
          git commit -m "Update file"
          git push origin test-workflow
