name: Create empty GitHub repo and clone monorepo into it

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: "The name of the repository to create"
        required: true
        type: string

env:
  GITHUB_TOKEN: ${{ secrets.DASK_ONBOARDING_PAT }}
  REPO_NAME: ${{ inputs.repo_name }}


jobs:
  create_and_clone_repo:
    runs-on: ubuntu-latest
    steps:
#      - name: Create empty repo
#        uses: actions/github-script@v7
#        with:
#          github-token: ${{ env.GITHUB_TOKEN }}
#          script: |
#            const repoName = '${{ env.REPO_NAME }}';
#            const response = await github.request('POST /orgs/{org}/repos', {
#                org: 'kartverket',
#                name: '${{ env.REPO_NAME }}',
#                description: 'This is your first repository',
#                visibility: 'public',
#                headers: {
#                  'X-GitHub-Api-Version': '2022-11-28'
#                }
#            });
#            console.log(`Response for creating repo ${repoName}:`, response);
      - name: Checkout the reference repository
        uses: actions/checkout@v4
        with:
          repository: kartverket/dask-monorepo-reference-setup
          path: 'cloned-repo'

      - name: Initialize new repository and push
        run: |
          cd cloned-repo
          git init
          git config --global user.name "DASK CI"
          git config --global user.email "noreply@kartverket.no"
          git remote rename origin old-origin
          git remote add origin https://github.com/kartverket/${{ env.REPO_NAME }}.git
          git push -u origin --all
          git push -u origin --tags


