name: Deploy image to apps repo

on:
  workflow_call:
    inputs:
      image_url:
        required: true
        type: string
      version_file_name:
        required: true
        type: string
      apps_repo:
        required: true
        type: string
      version_file_directory:
        description: "Directory where version file with image ref is stored"
        required: false
        default: "./versions"
        type: string
      identity:
        required: true
        type: string
      manual_deploy_trigger:
        type: string
        default: false

env:
  REGISTRY: ghcr.io
  APPS_REPO: ${{ inputs.apps_repo }}

jobs:
  deploy-image-to-apps-repo:
    name: Deploy image to apps repo
    runs-on: ubuntu-latest
    outputs:
      image_url: ${{ steps.set_output.outputs.image_url }}
    env:
      IDENTITY: ${{ inputs.identity }}
    steps:
      - uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f
        id: octo-sts
        with:
          scope: kartverket/${{ env.APPS_REPO }}
          identity: ${{ env.IDENTITY }}

      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          repository: kartverket/${{ env.APPS_REPO }}
          ref: main
          token: ${{ steps.octo-sts.outputs.token }}

      - name: Create file
        env:
          BRANCH: ${{ github.head_ref || github.ref_name }}
          MANUAL_DEPLOY_TRIGGER: ${{ inputs.manual_deploy_trigger }}
        run: |
          setup_directory () {
              DIRECTORY=${{ inputs.version_file_directory }}
              touch $DIRECTORY/${{ inputs.version_file_name }}
              echo "\"${{ env.REGISTRY }}/${{ github.repository }}@${{ steps.build-docker.outputs.digest }}\"" > $DIRECTORY/${{ inputs.version_file_name }} 
          }

          if [[ "${{ env.BRANCH }}" == "main" ]] || [[ "${{env.MANUAL_DEPLOY_TRIGGER}}" == "true" ]]; then
              setup_directory 
          fi

      - name: Commit and Push Changes
        run: |
          git config --global user.email "noreply@kartverket.no"
          git config --global user.name "DASK CI"
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update ${{ inputs.version_file_name }}"
            git push
          fi
