name: Fetch and Publish Product Team Data From GCP

on:
  workflow_dispatch:

env:
  AUTH_PROJECT_NUMBER: 149356773285
  PROJECT_ID: dataplattform-prod-9b1d
  SERVICE_ACCOUNT: dataplattform-deploy@dataplattform-prod-9b1d.iam.gserviceaccount.com
  WORKLOAD_IDENTITY_PROVIDER: projects/${AUTH_PROJECT_NUMBER}/locations/global/workloadIdentityPools/dataplattform-deploy-pool/providers/github-provider

jobs:
  fetch-teams-from-gcp:
    runs-on: ubuntu-latest
    steps:
      - name: wif-check
        id: wif-check
        run: |
          echo wif: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Heisann
        id: heisann
        run: echo "heisann!"
