name: Create empty GitHub repo and clone monorepo into it

on:
  workflow_dispatch:
    inputs:
      team_name:
        description: "The name of the repository to create"
        required: true
        type: string
      service_account:
        description: "The GCP service account connected to the identity pool that will be used by Terraform for authentication to GCP."
        required: true
        type: string
      auth_project_number:
        description: "The GCP Project Number used for authentication. A 12-digit number used as a unique identifier for the project. Used to find workload identity pool."
        required: true
        type: string

env:
  GITHUB_TOKEN: ${{ secrets.DASK_ONBOARDING_PAT }}
  TEAM_NAME: ${{ inputs.team_name }} # Lowercase-name-for-team
  AUTH_PROJECT_NUMBER: ${{ inputs.auth_project_number }}
  SERVICE_ACCOUNT: ${{ inputs.service_account }}
  STEP_ID: iam-setup # Must match step-id in dask-onboarding-service


jobs:
  send_success_message_to_pubsub:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
    steps:
      - name: Send success message to Pub/Sub
        uses: ./.github/workflows/publish-message-pubsub.yml
        with:
          auth_project_number: ${{ env.AUTH_PROJECT_NUMBER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
          team_name: ${{ env.TEAM_NAME }}
          step_id: ${{ env.STEP_ID }}



