name: Publish message to PubSub onboarding topic

on:
  workflow_call:
    inputs:
      service_account:
        description: "The GCP service account connected to the identity pool that will be used by Terraform for authentication to GCP."
        required: true
        type: string
      auth_project_number:
        description: "The GCP Project Number used for authentication. A 12-digit number used as a unique identifier for the project. Used to find workload identity pool."
        required: true
        type: string
      team_name:
        description: "The unique name representing the team that is undergoing the onboarding process to DASK."
        required: true
        type: string
      step_id:
        description: "The step id to notify completion for to the pub sub onboarding topic."
        required: true
        type: string
      params:
        description: "The params appended to by each step of the onboarding flow."
        required: false
        type: string
        default: "null"

env:
  AUTH_PROJECT_NUMBER: ${{ inputs.auth_project_number }}
  SERVICE_ACCOUNT: ${{ inputs.service_account }}
  TEAM_NAME: ${{ inputs.team_name }}
  STEP_ID: ${{ inputs.step_id }}
  PARAMS: ${{ inputs.params }}

jobs:
  publish_message_to_pubsub_onboarding_topic:
    name: Notify task completion to the onboarding PubSub-topic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish message
        uses: ./.github/workflows/publish-pubsub-message.yml
        with:
          service_account: env.SERVICE_ACCOUNT
          auth_project_number: env.AUTH_PROJECT_NUMBER
          pubsub_topic: onboarding_topic
          pubsub_message: '{ "team_name": "${{ env.TEAM_NAME }}", "step": "${{ env.STEP_ID }}", "params": ${{ env.PARAMS }} }'
