name: Pull Request Actions

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]

jobs:
  pharos-scan:
    name: Run Pharos with Required Permissions
    permissions:
      actions: read
      packages: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - name: "Run Pharos"
        uses: kartverket/pharos@v0.3.3
        with:
          allow_severity_level: high