name: Trigger Infrastructure Pub/Sub Event

on:
  workflow_call:
    inputs:
      event_source:
        description: The event source to publish on the flippity flip
        required: true
        type: string

env:
  PROJECT_ID: ${{ secrets.project_id }}
  AUTH_PROJECT_NUMBER: ${{ secrets.auth_project_number }}
  EVENT_SOURCE: ${{ inputs.event_source }}

jobs:
  publish_message_on_infrastructure_queue:
    name: Publish Message on Infrastructure Queue
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish message
        uses: ./.github/workflows/publish-pubsub-message.yml
        with:
          service_account: dataplattform-deploy@${{ env.PROJECT_ID }}.iam.gserviceaccount.com
          auth_project_number: env.AUTH_PROJECT_NUMBER
          pubsub_topic: onboarding_organization_topic
          pubsub_message: '{ "event_source": "${{ env.EVENT_SOURCE }}" }'
