name: Publish Entra ID Config Change Event

on:
  repository_dispatch:
    types: [ update_submodules ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  EVENT_SOURCE: entra-id-config

jobs:
  publish_team_change_message:
    name: Publish Team Change Message
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger Infrastructure Change
        uses: ./.github/workflows/trigger-infrastructure-pubsub-event.yml
        with:
          event_source: ${{ env.EVENT_SOURCE }}
