on:
  repository_dispatch:
    types: [ update_submodules ]
  workflow_dispatch:
    inputs:
      event_source:
        type: string
        required: true
        description: Event source to publish to queue
        default: entra-id-config

permissions:
  contents: read
  id-token: write

jobs:
  publish_team_change_message:
    name: Publish Team Change Message
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Infrastructure Change
        uses: ./.github/workflows/trigger-infrastructure-pubsub-event.yml
        with:
          event_source: ${{ inputs.event_source }}
