name: Publish Entra ID Config Change Event

on:
  repository_dispatch:
    types: [ update_submodules ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish_team_change_message:
    name: Publish Team Change Message
    uses: ./.github/workflows/trigger-infrastructure-pubsub-event.yml
    with:
      event_source: entra-id-config
